[build]
  command = "bun run build"
  publish = ".next"

# Handle Next.js routing
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variable configuration
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For handling API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
