name: Build and Deploy to Netlify

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install libvips (required by sharp)
        run: sudo apt-get update && sudo apt-get install -y libvips-dev

      - name: Install dependencies
        run: bun install

      - name: Install sharp
        run: bun add sharp

      - name: Install Netlify CLI
        run: bun add -g netlify-cli

      - name: Build with Netlify
        run: netlify build
        env:
          NODE_VERSION: 18
          NEXT_USE_NETLIFY_EDGE: true
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          # add any other required env variables here

      - name: Deploy to Netlify
        run: netlify deploy --dir=.netlify/output --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
